"""Map company names from user's Excel to NSE option-chain symbols."""
import json
import re
import pandas as pd

path = "/home/ubuntu/upload/NSE_FO_Options_Stocks_List-1.xlsx"
df = pd.read_excel(path)
names = [str(n).strip() for n in df["Stock Name"].dropna()]
names = [n for n in names if n.strip() and not n.lower().startswith(("note", "list", "source", "this"))]
print("name count:", len(names))

# Manual name -> NSE symbol mapping for all 208
MAPPING = {
    "Reliance Industries": "RELIANCE",
    "Bharti Airtel": "BHARTIARTL",
    "HDFC Bank": "HDFCBANK",
    "ICICI Bank": "ICICIBANK",
    "State Bank of India": "SBIN",
    "Tata Consultancy Services": "TCS",
    "Bajaj Finance": "BAJFINANCE",
    "Larsen & Toubro": "LT",
    "LIC of India": "LICI",
    "Hindustan Unilever": "HINDUNILVR",
    "Infosys": "INFY",
    "ITC": "ITC",
    "Kotak Mahindra Bank": "KOTAKBANK",
    "Axis Bank": "AXISBANK",
    "Maruti Suzuki India": "MARUTI",
    "Sun Pharmaceutical": "SUNPHARMA",
    "Tata Motors": "TATAMOTORS",
    "UltraTech Cement": "ULTRACEMCO",
    "HCL Technologies": "HCLTECH",
    "Asian Paints": "ASIANPAINT",
    "Titan Company": "TITAN",
    "NTPC": "NTPC",
    "Mahindra & Mahindra": "M&M",
    "Power Grid Corporation": "POWERGRID",
    "Wipro": "WIPRO",
    "ONGC": "ONGC",
    "Bajaj Finserv": "BAJAJFINSV",
    "Coal India": "COALINDIA",
    "Grasim Industries": "GRASIM",
    "Adani Enterprises": "ADANIENT",
    "Adani Ports and Special Economic Zone": "ADANIPORTS",
    "Divi's Laboratories": "DIVISLAB",
    "Hindalco Industries": "HINDALCO",
    "Bosch": "BOSCHLTD",
    "Tata Steel": "TATASTEEL",
    "JSW Steel": "JSWSTEEL",
    "BPCL": "BPCL",
    "Nestle India": "NESTLEIND",
    "Shriram Finance": "SHRIRAMFIN",
    "Dr Reddy's Laboratories": "DRREDDY",
    "Bharat Petroleum": "BPCL",
    "Havells India": "HAVELLS",
    "SBI Life Insurance": "SBILIFE",
    "Adani Green Energy": "ADANIGREEN",
    "Siemens": "SIEMENS",
    "Indian Oil Corporation": "IOC",
    "ICICI Prudential Life Insurance": "ICICIPRULI",
    "ICICI Lombard": "ICICIGI",
    "ABB India": "ABB",
    "DLF": "DLF",
    "HDFC Life Insurance": "HDFCLIFE",
    "Ambuja Cements": "AMBUJACEM",
    "GAIL (India)": "GAIL",
    "Jindal Steel and Power": "JINDALSTEL",
    "InterGlobe Aviation (IndiGo)": "INDIGO",
    "Zomato": "ZOMATO",
    "Balkrishna Industries": "BALKRISIND",
    "SBI Cards and Payment Services": "SBICARD",
    "Pidilite Industries": "PIDILITIND",
    "Varun Beverages": "VBL",
    "Persistent Systems": "PERSISTENT",
    "Bajaj Auto": "BAJAJ-AUTO",
    "Trent": "TRENT",
    "Cipla": "CIPLA",
    "Hero MotoCorp": "HEROMOTOCO",
    "HDFC Asset Management": "HDFCAMC",
    "Max Healthcare Institute": "MAXHEALTH",
    "Indian Railway Finance Corporation": "IRFC",
    "Indian Railway Catering and Tourism": "IRCTC",
    "TVS Motor Company": "TVSMOTOR",
    "Muthoot Finance": "MUTHOOTFIN",
    "Oracle Financial Services Software": "OFSS",
    "Larsen & Toubro Infotech": "LTIM",
    "Info Edge (India)": "NAUKRI",
    "Polycab India": "POLYCAB",
    "Bharat Electronics": "BEL",
    "Mphasis": "MPHASIS",
    "Colgate Palmolive (India)": "COLPAL",
    "Hindustan Aeronautics": "HAL",
    "Berger Paints India": "BERGEPAINT",
    "Lupin": "LUPIN",
    "United Spirits": "MCDOWELL-N",
    "Dixon Technologies (India)": "DIXON",
    "Bharat Heavy Electricals": "BHEL",
    "Tata Consumer Products": "TATACONSUM",
    "Bajaj Holdings and Investment": "BAJAJHLDNG",
    "Marico": "MARICO",
    "Avenue Supermarts (DMart)": "DMART",
    "Gland Pharma": "GLAND",
    "Cholamandalam Investment and Finance": "CHOLAFIN",
    "Godrej Consumer Products": "GODREJCP",
    "Britannia Industries": "BRITANNIA",
    "Aditya Birla Capital": "ABCAPITAL",
    "Eicher Motors": "EICHERMOT",
    "Godrej Properties": "GODREJPROP",
    "Bank of Baroda": "BANKBARODA",
    "Canara Bank": "CANBK",
    "Union Bank of India": "UNIONBANK",
    "Federal Bank": "FEDERALBNK",
    "PNB": "PNB",
    "IDFC First Bank": "IDFCFIRSTB",
    "Indian Bank": "INDIANB",
    "Vedanta": "VEDL",
    "Hindalco Industries": "HINDALCO",
    "JSW Energy": "JSWENERGY",
    "Adani Total Gas": "ATGL",
    "Power Finance Corporation": "PFC",
    "REC": "RECLTD",
    "NMDC": "NMDC",
    "Oil India": "OIL",
    "Gujarat Gas": "GUJGASLTD",
    "Adani Power": "ADANIPOWER",
    "NHPC": "NHPC",
    "SJVN": "SJVN",
    "Ircon International": "IRCON",
    "RVNL": "RVNL",
    "RailTel": "RAILTEL",
    "Tata Power": "TATAPOWER",
    "Torrent Power": "TORNTPWR",
    "CESC": "CESC",
    "Aurobindo Pharma": "AUROPHARMA",
    "Alkem Laboratories": "ALKEM",
    "Laurus Labs": "LAURUSLABS",
    "Natco Pharma": "NATCOPHARM",
    "Biocon": "BIOCON",
    "Apollo Hospitals": "APOLLOHOSP",
    "Narayana Hrudayalaya": "NH",
    "Fortis Healthcare": "FORTIS",
    "Max Financial Services": "MFSL",
    "SBI Cards": "SBICARD",
    "HDFC Bank": "HDFCBANK",
    "Suzlon Energy": "SUZLON",
    "Polycab India": "POLYCAB",
    "KPIT Technologies": "KPITTECH",
    "Tata Elxsi": "TATAELXSI",
    "Honeywell Automation India": "HONAUT",
    "Cyient": "CYIENT",
    "Birlasoft": "BSOFT",
    "Coforge": "COFORGE",
    "Tech Mahindra": "TECHM",
    "LTTS (L&T Technology Services)": "LTTS",
    "Tata Communications": "TATACOMM",
    "Jubilant FoodWorks": "JUBLFOOD",
    "Page Industries": "PAGEIND",
    "Voltas": "VOLTAS",
    "Blue Star": "BLUESTARCO",
    "Astral": "ASTRAL",
    "Supreme Industries": "SUPREMEIND",
    "KPR Mill": "KPRMILL",
    "Ramkrishna Forgings": "RKFORGE",
    "Glenmark Pharmaceuticals": "GLENMARK",
    "Abbott India": "ABBOTINDIA",
    "Pfizer": "PFIZER",
    "Sanofi India": "SANOFI",
    "Torrent Pharmaceuticals": "TORNTPHARM",
    "Jubilant Ingrevia": "JUBLINGREA",
    "Deepak Nitrite": "DEEPAKNTR",
    "SRF": "SRF",
    "PI Industries": "PIIND",
    "UPL": "UPL",
    "Aegis Logistics": "AEGISCHEM",
    "Gujarat Fluorochemicals": "FLUOROCHEM",
    "Navin Fluorine International": "NAVINFLUOR",
    "Century Textiles & Industries": "CENTURYTEX",
    "Dalmia Bharat": "DALBHARAT",
    "Shree Cement": "SHREECEM",
    "Ramco Cements": "RAMCOCEM",
    "JK Cement": "JKCEMENT",
    "ACC": "ACC",
    "Jubilant Foodworks": "JUBLFOOD",
    "PVR INOX": "PVRINOX",
    "IRB Infrastructure": "IRB",
    "Container Corporation of India": "CONCOR",
    "Shipping Corporation of India": "SCI",
    "Mazagon Dock Shipbuilders": "MAZDOCK",
    "Cochin Shipyard": "COCHINSHIP",
    "Garden Reach Shipbuilders": "GRSE",
    "Reliance Power": "RPOWER",
    "Jubilant Pharmova": "JUBLPHARMA",
    "Indus Towers": "INDUSTOWER",
    "Bharti Airtel": "BHARTIARTL",
    "InterGlobe Aviation": "INDIGO",
    "Zydus Lifesciences": "ZYDUSLIFE",
    "Minda Corporation": "MINDACORP",
    "Supreme Petrochem": "SPLPETRO",
    "Happiest Minds Technologies": "HAPPSTMNDS",
    "Newgen Software": "NEWGEN",
    "Route Mobile": "ROUTE",
    "Netweb Technologies": "NETWEB",
    "Glenmark Life Sciences": "GLS",
    "Astral Ltd": "ASTRAL",
    "Kalyan Jewellers": "KALYANKJIL",
    "CAMS (Computer Age Management)": "CAMS",
    "Ratnamani Metals": "RATNAMANI",
    "Praj Industries": "PRAJIND",
    "Fineotex Chemical": "FCL",
    "Fine Organic Industries": "FINEORG",
    "Elecon Engineering": "ELECON",
    "Sona BLW Precision": "SONACOMS",
    "Uno Minda": "UNOMINDA",
    "Exide Industries": "EXIDEIND",
    "Amara Raja Energy & Mobility": "ARE&M",
    "HBL Power Systems": "HBLPOWER",
    "Firstsource Solutions": "FSL",
    "Affle (India)": "AFFLE",
    "Easy Trip Planners (EaseMyTrip)": "EASEMYTRIP",
    "Carborundum Universal": "CARBORUNIV",
    "Timken India": "TIMKEN",
    "Schaeffler India": "SCHAEFFLER",
    " SKF India": "SKFINDIA",
    "CG Power and Industrial Solutions": "CGPOWER",
    "KEC International": "KEC",
    "Kalpataru Projects": "KALPATARO",
    "PNC Infratech": "PNCINFRA",
    "GMR Airports": "GMRINFRA",
    "Dabur India": "DABUR",
    "Emami": "EMAMILTD",
    "GSK Consumer Healthcare": "GSKCONS",
    "Jyothy Labs": "JYOTHYLAB",
    "United Breweries": "UBL",
    "Radico Khaitan": "RADICO",
    "Varun Beverages Ltd": "VBL",
    "Cholamandalam Financial": "CHOLAFIN",
    "Manappuram Finance": "MANAPPURAM",
    "CreditAccess Grameen": "CREDITACC",
    "Equitas Small Finance Bank": "EQUITASBNK",
    "AU Small Finance Bank": "AUBANK",
    "City Union Bank": "CUB",
    "Karur Vysya Bank": "KARURVYSYA",
    "South Indian Bank": "SOUTHBANK",
    "IDBI Bank": "IDBI",
    "Bank of Maharashtra": "MAHABANK",
    "Central Bank of India": "CENTRALBK",
    "Indian Overseas Bank": "IOB",
    "360 One WAM": "360ONE",
    "APL Apollo Tubes": "APLAPOLLO",
    "Adani Energy Solutions": "ADANIENSOL",
    "Adani Ports & SEZ": "ADANIPORTS",
    "Amber Enterprises": "AMBER",
    "Angel One": "ANGELONE",
    "Ashok Leyland": "ASHOKLEY",
    "BSE": "BSE",
    "Bajaj Holdings & Investments": "BAJAJHLDNG",
    "Bandhan Bank": "BANDHANBNK",
    "Bank of India": "BANKINDIA",
    "Bharat Dynamics": "BDL",
    "Bharat Forge": "BHARATFORG",
    "CDSL": "CDSL",
    "Cholamandalam Investment": "CHOLAFIN",
    "Crompton Greaves Consumer Electricals": "CROMPTON",
    "Cummins India": "CUMMINSIND",
    "Delhivery": "DELHIVERY",
    "Dixon Technologies": "DIXON",
    "Dr Reddys Laboratories": "DRREDDY",
    "Eternal (Zomato)": "ZOMATO",
    "Force Motors": "FORCEMOT",
    "Godfrey Phillips India": "GODFRYPHLP",
    "Hindustan Petroleum": "HINDPETRO",
    "Hindustan Zinc": "HINDZINC",
    "Hitachi Energy": "HITACHI",
    "Hyundai Motor India": "HYUNDAI",
    "ICICI Lombard General Insurance": "ICICIGI",
    "Indian Energy Exchange": "IEX",
    "Indian Hotels Company": "INDHOTEL",
    "IndusInd Bank": "INDUSINDBK",
    "Info Edge": "NAUKRI",
    "Inox Wind": "INOXWIND",
    "Jio Financial Services": "JIOFIN",
    "KEI Industries": "KEI",
    "KFin Technologies": "KFINTECH",
    "Kaynes Technology India": "KAYNES",
    "L&T Finance": "LTF",
    "LIC Housing Finance": "LICHSGFIN",
    "Lodha Developers": "LODHA",
    "MCX": "MCX",
    "Mankind Pharma": "MANKIND",
    "Motilal Oswal Financial Services": "MOTILALOFS",
    "NBCC (India)": "NBCC",
    "Nippon Life India AMC": "NIPPOINDIA",
    "Nykaa (FSN E-Commerce)": "NYKAA",
    "Oberoi Realty": "OBEROIRLTY",
    "One 97 Communications (Paytm)": "PAYTM",
    "PB Fintech (Policybazaar)": "POLICYBZR",
    "PG Electroplast": "PGEL",
    "PNB Housing Finance": "PNBHOUSING",
    "Patanjali Foods": "PATANJALI",
    "Petronet LNG": "PETRONET",
    "Phoenix Mills": "PHOENIXLTD",
    "Premier Energies": "PREMIERENE",
    "Prestige Estates Projects": "PRESTIGE",
    "RBL Bank": "RBLBANK",
    "Solar Industries": "SOLARINDS",
    "Swiggy": "SWIGGY",
    "Tata Motors Passenger Vehicles": "TATAMOTORS",
    "Titan": "TITAN",
    "Tube Investments of India": "TIINDIA",
    "UNO Minda": "UNOMINDA",
    "Vishal Mega Mart": "VMM",
    "Vodafone Idea": "IDEA",
    "Waaree Energies": "WAAREEENER",
    "Yes Bank": "YESBANK",
}

names = set(names)
mapped, unmapped = {}, []
for name in sorted(names):
    sym = MAPPING.get(name)
    if sym and sym not in mapped.values():
        mapped[name] = sym
    else:
        unmapped.append(name)

print("mapped:", len(mapped), "| unmapped:", len(unmapped))
for n in unmapped:
    print("  ?", n)

# Save final universe
symbols = sorted(mapped.values())
with open("/home/ubuntu/option_scalp/data/universe.json", "w") as f:
    json.dump(symbols, f, indent=1)
print("universe size:", len(symbols))
