"""Authoritative name->symbol mapping for the user's exact 208-name list.

Source: /home/ubuntu/upload/NSE_FO_Options_Stocks_List.xlsx (208 unique names).
Names are normalized (lower, strip, '&' variants) to catch spelling variants.
"""
import json

NAMES_PATH = "/tmp/names208.txt"
names = [n for n in open(NAMES_PATH).read().splitlines() if n.strip()]
assert len(names) == 208, len(names)

MAPPING = {
    "reliance industries": "RELIANCE",
    "bharti airtel": "BHARTIARTL",
    "hdfc bank": "HDFCBANK",
    "icici bank": "ICICIBANK",
    "state bank of india": "SBIN",
    "tata consultancy services": "TCS",
    "bajaj finance": "BAJFINANCE",
    "larsen & toubro": "LT",
    "larsen & toubro": "LT",
    "larsen and toubro": "LT",
    "lic of india": "LICI",
    "hindustan unilever": "HINDUNILVR",
    "sun pharmaceutical": "SUNPHARMA",
    "infosys": "INFY",
    "maruti suzuki": "MARUTI",
    "titan": "TITAN",
    "adani power": "ADANIPOWER",
    "mahindra & mahindra": "M&M",
    "mahindra and mahindra": "M&M",
    "adani ports & sez": "ADANIPORTS",
    "adani ports and sez": "ADANIPORTS",
    "adani enterprises": "ADANIENT",
    "kotak mahindra bank": "KOTAKBANK",
    "axis bank": "AXISBANK",
    "hcl technologies": "HCLTECH",
    "itc": "ITC",
    "ultratech cement": "ULTRACEMCO",
    "ntpc": "NTPC",
    "bajaj auto": "BAJAJ-AUTO",
    "jsw steel": "JSWSTEEL",
    "hindustan aeronautics": "HAL",
    "bajaj finserv": "BAJAJFINSV",
    "eternal (zomato)": "ZOMATO",
    "oil & natural gas corporation": "ONGC",
    "oil and natural gas corporation": "ONGC",
    "nestle india": "NESTLEIND",
    "bharat electronics": "BEL",
    "asian paints": "ASIANPAINT",
    "power grid corporation of india": "POWERGRID",
    "power grid corporation": "POWERGRID",
    "coal india": "COALINDIA",
    "avenue supermarts (dmart)": "DMART",
    "shriram finance": "SHRIRAMFIN",
    "tata steel": "TATASTEEL",
    "adani green energy": "ADANIGREEN",
    "hindustan zinc": "HINDZINC",
    "hindalco industries": "HINDALCO",
    "eicher motors": "EICHERMOT",
    "grasim industries": "GRASIM",
    "divis laboratories": "DIVISLAB",
    "divi's laboratories": "DIVISLAB",
    "interglobe aviation": "INDIGO",
    "adani energy solutions": "ADANIENSOL",
    "indian oil corporation": "IOC",
    "wipro": "WIPRO",
    "tvs motors": "TVSMOTOR",
    "sbi life insurance": "SBILIFE",
    "torrent pharmaceuticals": "TORNTPHARM",
    "dlf": "DLF",
    "pidilite industries": "PIDILITIND",
    "jio financial services": "JIOFIN",
    "solar industries": "SOLARINDS",
    "hyundai motor india": "HYUNDAI",
    "tech mahindra": "TECHM",
    "trent": "TRENT",
    "abb india": "ABB",
    "samvardhana motherson international": "MOTHERSON",
    "cholamandalam investment": "CHOLAFIN",
    "cholamandalam investment and finance": "CHOLAFIN",
    "varun beverages": "VBL",
    "varun beverages ltd": "VBL",
    "cummins india": "CUMMINSIND",
    "bse": "BSE",
    "hitachi energy": "HITACHI",
    "vodafone idea": "IDEA",
    "power finance corporation": "PFC",
    "bharat heavy electricals": "BHEL",
    "bharat petroleum": "BPCL",
    "polycab india": "POLYCAB",
    "britannia industries": "BRITANNIA",
    "ltimindtree": "LTIM",
    "lodha developers": "LODHA",
    "union bank of india": "UNIONBANK",
    "cg power & industrial solutions": "CGPOWER",
    "cg power and industrial solutions": "CGPOWER",
    "siemens": "SIEMENS",
    "apollo hospitals": "APOLLOHOSP",
    "punjab national bank": "PNB",
    "bank of baroda": "BANKBARODA",
    "bajaj holdings & investments": "BAJAJHLDNG",
    "bajaj holdings and investments": "BAJAJHLDNG",
    "tata motors passenger vehicles": "TMPV",
    "muthoot finance": "MUTHOOTFIN",
    "tata power": "TATAPOWER",
    "bosch": "BOSCHLTD",
    "hdfc life insurance": "HDFCLIFE",
    "cipla": "CIPLA",
    "irfc": "IRFC",
    "gail": "GAIL",
    "marico": "MARICO",
    "zydus lifesciences": "ZYDUSLIFE",
    "canara bank": "CANBK",
    "lupin": "LUPIN",
    "gmr airports": "GMRINFRA",
    "gmr airports infrastructure": "GMRINFRA",
    "indian bank": "INDIANB",
    "jindal steel & power": "JINDALSTEL",
    "jindal steel and power": "JINDALSTEL",
    "godrej consumer products": "GODREJCP",
    "ambuja cements": "AMBUJACEM",
    "hdfc amc": "HDFCAMC",
    "united spirits": "MCDOWELL-N",
    "tata consumer products": "TATACONSUM",
    "max healthcare institute": "MAXHEALTH",
    "mankind pharma": "MANKIND",
    "ge vernova t&d india": "GE Vernova",   # not yet in NSE F&O (verify below)
    "indian hotels company": "INDHOTEL",
    "aditya birla capital": "ABCAPITAL",
    "bharat forge": "BHARATFORG",
    "hero motocorp": "HEROMOTOCO",
    "vedanta": "VEDL",
    "indus towers": "INDUSTOWER",
    "jsw energy": "JSWENERGY",
    "oracle financial services software": "OFSS",
    "rec": "RECLTD",
    "shree cement": "SHREECEM",
    "laurus labs": "LAURUSLABS",
    "dr reddys laboratories": "DRREDDY",
    "nykaa (fsn e-commerce)": "NYKAA",
    "mazagon dock shipbuilders": "MAZDOCK",
    "ashok leyland": "ASHOKLEY",
    "aurobindo pharma": "AUROPHARMA",
    "federal bank": "FEDERALBNK",
    "persistent systems": "PERSISTENT",
    "dixon technologies": "DIXON",
    "one 97 communications (paytm)": "PAYTM",
    "hindustan petroleum": "HINDPETRO",
    "icici lombard general insurance": "ICICIGI",
    "info edge": "NAUKRI",
    "swiggy": "SWIGGY",
    "indusind bank": "INDUSINDBK",
    "srf": "SRF",
    "nhpc": "NHPC",
    "au small finance bank": "AUBANK",
    "havells india": "HAVELLS",
    "waaree energies": "WAAREEENER",
    "l&t finance": "LTF",
    "dabur india": "DABUR",
    "nmdc": "NMDC",
    "nippon life india amc": "NIPPOINDIA",
    "pb fintech (policybazaar)": "POLICYBZR",
    "icici prudential life insurance": "ICICIPRULI",
    "idfc first bank": "IDFCFIRSTB",
    "prestige estates projects": "PRESTIGE",
    "oil india": "OIL",
    "fortis healthcare": "FORTIS",
    "yes bank": "YESBANK",
    "steel authority of india (sail)": "SAIL",
    "biocon": "BIOCON",
    "mcx": "MCX",
    "phoenix mills": "PHOENIXLTD",
    "alkem laboratories": "ALKEM",
    "uno minda": "UNOMINDA",
    "oberoi realty": "OBEROIRLTY",
    "godrej properties": "GODREJPROP",
    "kalyan jewellers": "KALYANKJIL",
    "suzlon energy": "SUZLON",
    "glenmark pharmaceuticals": "GLENMARK",
    "nalco": "NALCO",
    "sbi cards": "SBICARD",
    "sbi cards and payment services": "SBICARD",
    "bank of india": "BANKINDIA",
    "coforge": "COFORGE",
    "colgate-palmolive india": "COLPAL",
    "radico khaitan": "RADICO",
    "tube investments of india": "TIINDIA",
    "max financial services": "MFSL",
    "apl apollo tubes": "APLAPOLLO",
    "motilal oswal financial services": "MOTILALOFS",
    "upl": "UPL",
    "vishal mega mart": "VMM",
    "rail vikas nigam": "RVNL",
    "premier energies": "PREMIERENE",
    "kei industries": "KEI",
    "360 one wam": "360ONE",
    "bharat dynamics": "BDL",
    "mphasis": "MPHASIS",
    "page industries": "PAGEIND",
    "sona blw precision forgings": "SONACOMS",
    "supreme industries": "SUPREMEIND",
    "voltas": "VOLTAS",
    "petronet lng": "PETRONET",
    "pi industries": "PIIND",
    "container corporation of india": "CONCOR",
    "astral": "ASTRAL",
    "patanjali foods": "PATANJALI",
    "cochin shipyard": "COCHINSHIP",
    "delhivery": "DELHIVERY",
    "manappuram finance": "MANAPPURAM",
    "blue star": "BLUESTARCO",
    "dalmia bharat": "DALBHARAT",
    "ireda": "IREDA",
    "godfrey phillips india": "GODFRYPHLP",
    "lic housing finance": "LICHSGFIN",
    "jubilant foodworks": "JUBLFOOD",
    "cdsl": "CDSL",
    "angel one": "ANGELONE",
    "bandhan bank": "BANDHANBNK",
    "pnb housing finance": "PNBHOUSING",
    "amber enterprises": "AMBER",
    "nbcc (india)": "NBCC",
    "kaynes technology india": "KAYNES",
    "tata elxsi": "TATAELXSI",
    "rbl bank": "RBLBANK",
    "force motors": "FORCEMOT",
    "cams": "CAMS",
    "kpit technologies": "KPITTECH",
    "pg electroplast": "PGEL",
    "kfin technologies": "KFINTECH",
    "crompton greaves consumer electricals": "CROMPTON",
    "inox wind": "INOXWIND",
    "indian energy exchange": "IEX",
}

norm = {n.lower().strip() for n in names}
mapped = {n: MAPPING[n.lower().strip()] for n in names if n.lower().strip() in MAPPING}
unmapped = [n for n in names if n.lower().strip() not in MAPPING]
print("names:", len(names), "| mapped:", len(mapped), "| unmapped:", len(unmapped))
for n in unmapped:
    print("  ?", n)

symbols = sorted(set(mapped.values()))
print("unique symbols:", len(symbols))
json.dump({"names": sorted(set(names)), "symbols": symbols,
           "name_to_symbol": mapped},
          open("data/universe_final.json", "w"), indent=1)
print("saved data/universe_final.json")
